{% set version = "0.99.0" %}

package:
  name: contextily
  version: {{ version }}

source:
  fn: contextily-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 68caa2747374a7b42aba98f3030720673ba045313ad7382b1ea9ad451d0a7873

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cartopy
    - geopy
    - pandas
    - pillow
    - rasterio
    - six
    - mercantile

test:
  imports:
    - contextily

about:
  home: https://github.com/darribas/contextily
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Context geo-tiles in Python.'
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
