{% set version = "1.0rc1" %}

package:
  name: contextily
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/contextily/contextily-{{ version }}.tar.gz
  sha256: 1f0895a59b01b421e069c600fcfa6f4edf567509ec667210981b61e61195270a

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - cartopy
    - geopy
    - mercantile
    - pandas
    - pillow
    - rasterio
    - requests

test:
  imports:
    - contextily

about:
  home: https://github.com/darribas/contextily
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Context geo-tiles in Python'
  license_family: BSD

extra:
  recipe-maintainers:
    - darribas
    - ocefpaf
    - jorisvandenbossche
