# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "H8edKEJUgA7Hg/RbVh8t85O+J5wmRPdMhfdLAvyVg5MuTbnEuR9jfBvETbcfMLalvquwWw88xNBcVI6TM+pHwKaU9+sRKiksREHQ9R/xi4IqEiBVVVCY6YwmPlJ+vj00FCUn4WR2EicBvKXb4le++C6C7jksuQJ+mDlAkh2zicWWPZoca22xu0u7uQe2LWd1Hfm1Nd+bMiR7ICET1dcN6x7ClWYLUCkolr4oKw6Tc9ymAY+/+eUznJDMOPrc4OKfFl+iDNbUcqExxBaovGMGQPow15PPA2uZn5PYp6cI+X+3bywzLcDbv1yJ8/driVIhi/dgFpIgdKsjoBGVo538UmOB8Z2qfbvmtKOgQNTxSpf+dR9g+OlVjVPV7P57fGjj/A1+M28xYQ+eC84CIecZ2wyel9JorPHen0A+gFr0tYVrgZWXzBcKZ3G1tIApPVD73gfOyir1PN8Nnn4gIlva+rc7+NEeIE38JLeRfYmjUJ+EVflcGhcWKGqn3m4pdR0DZ+pVJuUuS24KaF515wkaD0tIqBr4bCrTsHjof76TDl3cSFRcPXmqFohFGPq51xVtnnXh3BrNPU7gUd1BIiN5GVoLH2ePaGypLPnMoxayY+MN8hNMuX69Bok0ceLPwhXyai4re1b+nFa/5kW20rlQznZ72KCAWoj9ekj7YEqPTOk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
