travis:
  secure:
    BINSTAR_TOKEN: dTvcdHUV97pQOwfUlD0+eo0XHNIKzjm22Dx630wlb+oDD8GlxIG3qxRrJrEutM695dte+v0xcE6/AsF/yViknFSIQLpUb3Ogyt9Dcnz2LdeQtUy7hR0GU59KT8TBAqmKDi2wMuHKOlefR3e77cFSNQQ/pRPBpIs2XGIFEDS3YTuKV0zqzjWwmLXw+0CHeB/lh5yZ7AdsyVsmVSDkhKF4R5/c9CN6miKaCT64ogWbBcXchLexT1qgRrIFTeqnjZvvkL0adAmnHBQDsvKkgF5QdwYQmunsAFeGh7b1Kn7DGPLvNU24PN2JBwptWueHr8HNfFzub7Fl8A+EFiw5ad7J4asWzJ/DYl6ZITqUHxBJaD23IaXXX8mhAxSOoUbkD2eXRhQpIy7+XttBEntbIyTTHPME2Erf93N3Ehc93VlEgGhaN/eY5coRzQRjfE4c3lbIRV0HeWl7mDP/RIwR2CXv++mi6tbEwDve6WAl9NkODCwvlbK7aKlT5XBAuKIhB/PNt6ymaWrhypm2MD6FwVHHNSmg/fxl5XIPpoVPatb85aZ78cdYW+eJlTaMIr9QShVzxeXVRNb+vhT7gwFpc+QyWhlQOtFAegDBEkX8HxCyNvG8wAXJy4nwHAA7WdG0iQHGL48hHrl92jHydhyhkgTP1AEGIxDcRjr+osUHRxzaewQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
