travis:
  secure:
    BINSTAR_TOKEN: H8edKEJUgA7Hg/RbVh8t85O+J5wmRPdMhfdLAvyVg5MuTbnEuR9jfBvETbcfMLalvquwWw88xNBcVI6TM+pHwKaU9+sRKiksREHQ9R/xi4IqEiBVVVCY6YwmPlJ+vj00FCUn4WR2EicBvKXb4le++C6C7jksuQJ+mDlAkh2zicWWPZoca22xu0u7uQe2LWd1Hfm1Nd+bMiR7ICET1dcN6x7ClWYLUCkolr4oKw6Tc9ymAY+/+eUznJDMOPrc4OKfFl+iDNbUcqExxBaovGMGQPow15PPA2uZn5PYp6cI+X+3bywzLcDbv1yJ8/driVIhi/dgFpIgdKsjoBGVo538UmOB8Z2qfbvmtKOgQNTxSpf+dR9g+OlVjVPV7P57fGjj/A1+M28xYQ+eC84CIecZ2wyel9JorPHen0A+gFr0tYVrgZWXzBcKZ3G1tIApPVD73gfOyir1PN8Nnn4gIlva+rc7+NEeIE38JLeRfYmjUJ+EVflcGhcWKGqn3m4pdR0DZ+pVJuUuS24KaF515wkaD0tIqBr4bCrTsHjof76TDl3cSFRcPXmqFohFGPq51xVtnnXh3BrNPU7gUd1BIiN5GVoLH2ePaGypLPnMoxayY+MN8hNMuX69Bok0ceLPwhXyai4re1b+nFa/5kW20rlQznZ72KCAWoj9ekj7YEqPTOk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
